[project]
name = "scplot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anndata>=0.10.9",
    "lets-plot>=4.5.1",
    "scanpy>=1.10.3",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.2",
]
